---
version: '3'

services:
  streamlit:
    container_name: streamlit
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/streamlit:latest
    ports:
      - 8501:8501
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - /usr/local/bin/streamlit
    command:
      - hello
